### ISSUE TITLE
Algorithm should be copy or create should take a reference

### ISSUE THREAD

**Issue by m4b** [CurrySoftware/rust-stemmers#2]
Otherwise there is no way to create a stemmer from a reference

And thanks for the crate !

**Comment by JDemler** [comment]
Yes obviously...
This was already in the code but not published on crates.io, sorry.

Find version 1.0.2, that implements `Copy` for `Algorithm` [here](https://crates.io/crates/rust-stemmers/1.0.2)

**Comment by m4b** [comment]
Awesome, thanks!
